import { requestJson as api } from './api-client.mjs';
const esc=s=>String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function qrUnitId(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.hash.match(/^#unit\/([a-f0-9-]{36})$/i)?.[1] || null:null;}catch{return null;}}
export function showStockWalk(app,id){
 let cancelled=false,stream,frame,busy=false,walk;
 const stop=()=>{cancelled=true;cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop());};
 const alive=()=>!cancelled && location.hash===`#stockwalk${id?'/'+id:''}`;
 const init=async()=>{
  app.innerHTML='<p role="status">Loading stock walk…</p>';
  try{
   if(!id){const locations=await api('/api/locations');if(!alive())return;app.innerHTML='<a class="back" href="#menu">Menu</a><h1>Start stock walk</h1><p>Select the lot you are walking. Each scanned unit will be assigned to this location. Unscanned units stay unchanged.</p><form id="walk-start" class="panel"><label>Location<select name="locationId" required><option value="">Choose a location</option>'+locations.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')+'</select></label><button>Start stock walk</button><p class="error" role="alert"></p></form>';
    app.querySelector('#walk-start').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;try{const created=await api('/api/stock-walks','POST',{locationId:form.elements.locationId.value});if(alive())location.hash='#stockwalk/'+created.id;}catch(error){if(alive()){form.querySelector('.error').textContent=error.message;button.disabled=false;}}};return;
   }
   walk=await api('/api/stock-walks/'+id);if(!alive())return;
   app.innerHTML=`<a class="back" href="#menu">Menu</a><h1>Stock walk: ${esc(walk.locationName)}</h1><p>Started by ${esc(walk.employeeName)}</p><p id="walk-count" role="status"></p><section id="walk-controls" class="panel" ${walk.completedAt?'hidden':''}><p>Scan each unit's Lot Rot QR tag. A location update is saved immediately after each successful scan.</p><button id="walk-camera">Start scanning</button><div id="walk-camera-panel" hidden><video id="walk-video" autoplay muted playsinline></video><button id="walk-pause" class="secondary">Pause camera</button></div><p id="walk-message" role="status" aria-live="polite"></p><form id="walk-manual"><label>Stock number or VIN<input name="stock" required autocomplete="off"></label><button>Add scanned unit</button></form><button id="walk-complete">Complete stock walk</button></section><section class="panel"><h2>Scanned units</h2><div id="walk-scans"></div></section>${walk.completedAt?'<a class="button" href="#stockwalk">Start another stock walk</a>':''}`;
   const message=app.querySelector('#walk-message'),count=app.querySelector('#walk-count'),scans=app.querySelector('#walk-scans');
   const paint=()=>{count.textContent=`${walk.scans.length} unique units scanned${walk.completedAt?' · Stock walk complete':''}`;scans.innerHTML=walk.scans.length?walk.scans.map(s=>`<p><strong>${esc(s.stockNumber)}</strong> → ${esc(s.locationName)}</p>`).join(''):'<p>No units scanned yet.</p>';};paint();if(walk.completedAt)return;
   const scanned=new Set(walk.scans.map(s=>s.unitId));let lastCode='',lastTime=0;
   const save=async unitId=>{if(busy)return;if(scanned.has(unitId)){message.textContent='Already scanned in this walk.';return;}busy=true;message.textContent='Saving location…';try{const result=await api('/api/stock-walks/'+id+'/scan','POST',{unitId});window.dispatchEvent(new CustomEvent('unit-updated',{detail:result.unit}));if(alive()){walk=result.walk;scanned.add(unitId);paint();message.textContent=`${result.unit.stockNumber} saved at ${walk.locationName}. Scan the next unit.`;}}catch(error){if(alive())message.textContent=error.message;}finally{busy=false;}};
   app.querySelector('#walk-manual').onsubmit=async e=>{e.preventDefault();if(busy)return;const text=e.target.elements.stock.value.trim().toLowerCase();try{const units=await api('/api/units');if(!alive())return;const unit=units.find(u=>[u.stockNumber,u.vin].some(v=>v.toLowerCase()===text));if(!unit){message.textContent='Stock number or VIN not found in your dealership.';return;}await save(unit.id);if(alive())e.target.reset();}catch(error){if(alive())message.textContent=error.message;}};
   const pause=()=>{cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop());stream=null;app.querySelector('#walk-camera-panel').hidden=true;app.querySelector('#walk-camera').disabled=false;};
   app.querySelector('#walk-pause').onclick=pause;
   app.querySelector('#walk-camera').onclick=async()=>{
    const button=app.querySelector('#walk-camera');if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||typeof window.jsQR!=='function'){message.textContent='Camera unavailable. Use a secure connection and allow camera access, or enter the stock number.';return;}button.disabled=true;
    try{const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(!alive()){next.getTracks().forEach(t=>t.stop());return;}stream=next;const video=app.querySelector('#walk-video');video.srcObject=stream;app.querySelector('#walk-camera-panel').hidden=false;await video.play();message.textContent='Point the camera at each unit’s QR tag.';
     const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});let lastFrame=0;
     const tick=time=>{if(!alive()||!stream)return;try{if(!busy&&video.readyState>=2&&video.videoWidth&&time-lastFrame>=125){lastFrame=time;const scale=Math.min(1,720/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);context.drawImage(video,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height),code=window.jsQR(pixels.data,pixels.width,pixels.height,{inversionAttempts:'attemptBoth'});if(code&&(code.data!==lastCode||time-lastTime>2500)){lastCode=code.data;lastTime=time;const unitId=qrUnitId(code.data);if(unitId)void save(unitId);else message.textContent='This is not a Lot Rot unit QR tag.';}}}catch{message.textContent='Keep the QR tag in view.';}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
    }catch{if(alive()){pause();message.textContent='Could not open camera. Allow access and try again.';}}
   };
   app.querySelector('#walk-complete').onclick=async()=>{if(busy){message.textContent='Wait for the current unit to finish saving.';return;}const button=app.querySelector('#walk-complete');button.disabled=true;pause();try{await api('/api/stock-walks/'+id+'/complete','POST',{});if(alive()){stop();showStockWalk(app,id);}}catch(error){if(alive()){message.textContent=error.message;button.disabled=false;}}};
  }catch(error){if(alive())app.innerHTML=`<a href="#menu">Menu</a><p class="error">${esc(error.message)}</p>`;}
 };
 void init();return stop;
}
